version: '3.8'

services:
  api:
    image: datascientest/fastapi:1.0.0
    container_name: api_ds_fastapi
    ports:
      - "8000:8000"
    networks:
      - test_network

  test_auth:
    image: my_image_auth
    container_name: test_auth_container
    environment:
      - API_ADDRESS=api
      - API_PORT=8000
      - LOG=1
    volumes:
      - ./logs:/logs
    networks:
      - test_network
    depends_on:
      - api

  test_authz:
    image: my_image_authz
    container_name: test_authz_container
    environment:
      - API_ADDRESS=api
      - API_PORT=8000
      - LOG=1
    volumes:
      - ./logs:/logs
    networks:
      - test_network
    depends_on:
      - api

  test_content:
    image: my_image_content
    container_name: test_content_container
    environment:
      - API_ADDRESS=api
      - API_PORT=8000
      - LOG=1
    volumes:
      - ./logs:/logs
    networks:
      - test_network
    depends_on:
      - api

networks:
  test_network:
    driver: bridge

volumes:
  logs:
    driver: local
